spring.application.name=EcommerceApi
spring.datasource.url=jdbc:mysql://localhost:3306/ecommercedb?useSSL=false&serverTimezone=UTC

# XAMPP default MySQL credentials
spring.datasource.username=root
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
